In [ ]:
import pandas as pd

In [1]:
print('Hello world')

Hello world

In [14]:
import pandas as pd 
#df = pd.read_csv('Pokemon_data.csv')
#print(df.head(4))
#print(df.tail(2))
#df_ex = pd.read_excel('Test_user.xlsx')
#print (df_ex.head())
df_a = pd.read_csv('Pokemon_data.txt',sep='\t')
print(df_a)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [19]:
# Read Headers
print(df_a.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [27]:
#Read each column
print(df_a[['Name','Type 1','HP']])

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [33]:
##Read Each row
print(df_a.iloc[1:3])

   #      Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
1  2   Ivysaur  Grass  Poison  60      62       63       80       80     60
2  3  Venusaur  Grass  Poison  80      82       83      100      100     80

   Generation  Legendary
1           1      False
2           1      False

In [34]:
## Read for specific location (row and column)
print(df_a.iloc[2,1])

Venusaur

In [2]:
import pandas as pd
df = pd.read_csv('Pokemon_data.csv')
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [41]:
for index,row in df_a.iterrows():
    print(index,row[['Name','HP']])

0 Name    Bulbasaur
HP             45
Name: 0, dtype: object
1 Name    Ivysaur
HP           60
Name: 1, dtype: object
2 Name    Venusaur
HP            80
Name: 2, dtype: object
3 Name    VenusaurMega Venusaur
HP                         80
Name: 3, dtype: object
4 Name    Charmander
HP              39
Name: 4, dtype: object
5 Name    Charmeleon
HP              58
Name: 5, dtype: object
6 Name    Charizard
HP             78
Name: 6, dtype: object
7 Name    CharizardMega Charizard X
HP                             78
Name: 7, dtype: object
8 Name    CharizardMega Charizard Y
HP                             78
Name: 8, dtype: object
9 Name    Squirtle
HP            44
Name: 9, dtype: object
10 Name    Wartortle
HP             59
Name: 10, dtype: object
11 Name    Blastoise
HP             79
Name: 11, dtype: object
12 Name    BlastoiseMega Blastoise
HP                           79
Name: 12, dtype: object
13 Name    Caterpie
HP            45
Name: 13, dtype: object
14 Name    Metapod
HP           50
Name: 14, dtype: object
15 Name    Butterfree
HP              60
Name: 15, dtype: object
16 Name    Weedle
HP          40
Name: 16, dtype: object
17 Name    Kakuna
HP          45
Name: 17, dtype: object
18 Name    Beedrill
HP            65
Name: 18, dtype: object
19 Name    BeedrillMega Beedrill
HP                         65
Name: 19, dtype: object
20 Name    Pidgey
HP          40
Name: 20, dtype: object
21 Name    Pidgeotto
HP             63
Name: 21, dtype: object
22 Name    Pidgeot
HP           83
Name: 22, dtype: object
23 Name    PidgeotMega Pidgeot
HP                       83
Name: 23, dtype: object
24 Name    Rattata
HP           30
Name: 24, dtype: object
25 Name    Raticate
HP            55
Name: 25, dtype: object
26 Name    Spearow
HP           40
Name: 26, dtype: object
27 Name    Fearow
HP          65
Name: 27, dtype: object
28 Name    Ekans
HP         35
Name: 28, dtype: object
29 Name    Arbok
HP         60
Name: 29, dtype: object
30 Name    Pikachu
HP           35
Name: 30, dtype: object
31 Name    Raichu
HP          60
Name: 31, dtype: object
32 Name    Sandshrew
HP             50
Name: 32, dtype: object
33 Name    Sandslash
HP             75
Name: 33, dtype: object
34 Name    Nidoran (Female)
HP                    55
Name: 34, dtype: object
35 Name    Nidorina
HP            70
Name: 35, dtype: object
36 Name    Nidoqueen
HP             90
Name: 36, dtype: object
37 Name    Nidoran (Male)
HP                  46
Name: 37, dtype: object
38 Name    Nidorino
HP            61
Name: 38, dtype: object
39 Name    Nidoking
HP            81
Name: 39, dtype: object
40 Name    Clefairy
HP            70
Name: 40, dtype: object
41 Name    Clefable
HP            95
Name: 41, dtype: object
42 Name    Vulpix
HP          38
Name: 42, dtype: object
43 Name    Ninetales
HP             73
Name: 43, dtype: object
44 Name    Jigglypuff
HP             115
Name: 44, dtype: object
45 Name    Wigglytuff
HP             140
Name: 45, dtype: object
46 Name    Zubat
HP         40
Name: 46, dtype: object
47 Name    Golbat
HP          75
Name: 47, dtype: object
48 Name    Oddish
HP          45
Name: 48, dtype: object
49 Name    Gloom
HP         60
Name: 49, dtype: object
50 Name    Vileplume
HP             75
Name: 50, dtype: object
51 Name    Paras
HP         35
Name: 51, dtype: object
52 Name    Parasect
HP            60
Name: 52, dtype: object
53 Name    Venonat
HP           60
Name: 53, dtype: object
54 Name    Venomoth
HP            70
Name: 54, dtype: object
55 Name    Diglett
HP           10
Name: 55, dtype: object
56 Name    Dugtrio
HP           35
Name: 56, dtype: object
57 Name    Meowth
HP          40
Name: 57, dtype: object
58 Name    Persian
HP           65
Name: 58, dtype: object
59 Name    Psyduck
HP           50
Name: 59, dtype: object
60 Name    Golduck
HP           80
Name: 60, dtype: object
61 Name    Mankey
HP          40
Name: 61, dtype: object
62 Name    Primeape
HP            65
Name: 62, dtype: object
63 Name    Growlithe
HP             55
Name: 63, dtype: object
64 Name    Arcanine
HP            90
Name: 64, dtype: object
65 Name    Poliwag
HP           40
Name: 65, dtype: object
66 Name    Poliwhirl
HP             65
Name: 66, dtype: object
67 Name    Poliwrath
HP             90
Name: 67, dtype: object
68 Name    Abra
HP        25
Name: 68, dtype: object
69 Name    Kadabra
HP           40
Name: 69, dtype: object
70 Name    Alakazam
HP            55
Name: 70, dtype: object
71 Name    AlakazamMega Alakazam
HP                         55
Name: 71, dtype: object
72 Name    Machop
HP          70
Name: 72, dtype: object
73 Name    Machoke
HP           80
Name: 73, dtype: object
74 Name    Machamp
HP           90
Name: 74, dtype: object
75 Name    Bellsprout
HP              50
Name: 75, dtype: object
76 Name    Weepinbell
HP              65
Name: 76, dtype: object
77 Name    Victreebel
HP              80
Name: 77, dtype: object
78 Name    Tentacool
HP             40
Name: 78, dtype: object
79 Name    Tentacruel
HP              80
Name: 79, dtype: object
80 Name    Geodude
HP           40
Name: 80, dtype: object
81 Name    Graveler
HP            55
Name: 81, dtype: object
82 Name    Golem
HP         80
Name: 82, dtype: object
83 Name    Ponyta
HP          50
Name: 83, dtype: object
84 Name    Rapidash
HP            65
Name: 84, dtype: object
85 Name    Slowpoke
HP            90
Name: 85, dtype: object
86 Name    Slowbro
HP           95
Name: 86, dtype: object
87 Name    SlowbroMega Slowbro
HP                       95
Name: 87, dtype: object
88 Name    Magnemite
HP             25
Name: 88, dtype: object
89 Name    Magneton
HP            50
Name: 89, dtype: object
90 Name    Farfetch'd
HP              52
Name: 90, dtype: object
91 Name    Doduo
HP         35
Name: 91, dtype: object
92 Name    Dodrio
HP          60
Name: 92, dtype: object
93 Name    Seel
HP        65
Name: 93, dtype: object
94 Name    Dewgong
HP           90
Name: 94, dtype: object
95 Name    Grimer
HP          80
Name: 95, dtype: object
96 Name    Muk
HP      105
Name: 96, dtype: object
97 Name    Shellder
HP            30
Name: 97, dtype: object
98 Name    Cloyster
HP            50
Name: 98, dtype: object
99 Name    Gastly
HP          30
Name: 99, dtype: object
100 Name    Haunter
HP           45
Name: 100, dtype: object
101 Name    Gengar
HP          60
Name: 101, dtype: object
102 Name    GengarMega Gengar
HP                     60
Name: 102, dtype: object
103 Name    Onix
HP        35
Name: 103, dtype: object
104 Name    Drowzee
HP           60
Name: 104, dtype: object
105 Name    Hypno
HP         85
Name: 105, dtype: object
106 Name    Krabby
HP          30
Name: 106, dtype: object
107 Name    Kingler
HP           55
Name: 107, dtype: object
108 Name    Voltorb
HP           40
Name: 108, dtype: object
109 Name    Electrode
HP             60
Name: 109, dtype: object
110 Name    Exeggcute
HP             60
Name: 110, dtype: object
111 Name    Exeggutor
HP             95
Name: 111, dtype: object
112 Name    Cubone
HP          50
Name: 112, dtype: object
113 Name    Marowak
HP           60
Name: 113, dtype: object
114 Name    Hitmonlee
HP             50
Name: 114, dtype: object
115 Name    Hitmonchan
HP              50
Name: 115, dtype: object
116 Name    Lickitung
HP             90
Name: 116, dtype: object
117 Name    Koffing
HP           40
Name: 117, dtype: object
118 Name    Weezing
HP           65
Name: 118, dtype: object
119 Name    Rhyhorn
HP           80
Name: 119, dtype: object
120 Name    Rhydon
HP         105
Name: 120, dtype: object
121 Name    Chansey
HP          250
Name: 121, dtype: object
122 Name    Tangela
HP           65
Name: 122, dtype: object
123 Name    Kangaskhan
HP             105
Name: 123, dtype: object
124 Name    KangaskhanMega Kangaskhan
HP                            105
Name: 124, dtype: object
125 Name    Horsea
HP          30
Name: 125, dtype: object
126 Name    Seadra
HP          55
Name: 126, dtype: object
127 Name    Goldeen
HP           45
Name: 127, dtype: object
128 Name    Seaking
HP           80
Name: 128, dtype: object
129 Name    Staryu
HP          30
Name: 129, dtype: object
130 Name    Starmie
HP           60
Name: 130, dtype: object
131 Name    Mr. Mime
HP            40
Name: 131, dtype: object
132 Name    Scyther
HP           70
Name: 132, dtype: object
133 Name    Jynx
HP        65
Name: 133, dtype: object
134 Name    Electabuzz
HP              65
Name: 134, dtype: object
135 Name    Magmar
HP          65
Name: 135, dtype: object
136 Name    Pinsir
HP          65
Name: 136, dtype: object
137 Name    PinsirMega Pinsir
HP                     65
Name: 137, dtype: object
138 Name    Tauros
HP          75
Name: 138, dtype: object
139 Name    Magikarp
HP            20
Name: 139, dtype: object
140 Name    Gyarados
HP            95
Name: 140, dtype: object
141 Name    GyaradosMega Gyarados
HP                         95
Name: 141, dtype: object
142 Name    Lapras
HP         130
Name: 142, dtype: object
143 Name    Ditto
HP         48
Name: 143, dtype: object
144 Name    Eevee
HP         55
Name: 144, dtype: object
145 Name    Vaporeon
HP           130
Name: 145, dtype: object
146 Name    Jolteon
HP           65
Name: 146, dtype: object
147 Name    Flareon
HP           65
Name: 147, dtype: object
148 Name    Porygon
HP           65
Name: 148, dtype: object
149 Name    Omanyte
HP           35
Name: 149, dtype: object
150 Name    Omastar
HP           70
Name: 150, dtype: object
151 Name    Kabuto
HP          30
Name: 151, dtype: object
152 Name    Kabutops
HP            60
Name: 152, dtype: object
153 Name    Aerodactyl
HP              80
Name: 153, dtype: object
154 Name    AerodactylMega Aerodactyl
HP                             80
Name: 154, dtype: object
155 Name    Snorlax
HP          160
Name: 155, dtype: object
156 Name    Articuno
HP            90
Name: 156, dtype: object
157 Name    Zapdos
HP          90
Name: 157, dtype: object
158 Name    Moltres
HP           90
Name: 158, dtype: object
159 Name    Dratini
HP           41
Name: 159, dtype: object
160 Name    Dragonair
HP             61
Name: 160, dtype: object
161 Name    Dragonite
HP             91
Name: 161, dtype: object
162 Name    Mewtwo
HP         106
Name: 162, dtype: object
163 Name    MewtwoMega Mewtwo X
HP                      106
Name: 163, dtype: object
164 Name    MewtwoMega Mewtwo Y
HP                      106
Name: 164, dtype: object
165 Name    Mew
HP      100
Name: 165, dtype: object
166 Name    Chikorita
HP             45
Name: 166, dtype: object
167 Name    Bayleef
HP           60
Name: 167, dtype: object
168 Name    Meganium
HP            80
Name: 168, dtype: object
169 Name    Cyndaquil
HP             39
Name: 169, dtype: object
170 Name    Quilava
HP           58
Name: 170, dtype: object
171 Name    Typhlosion
HP              78
Name: 171, dtype: object
172 Name    Totodile
HP            50
Name: 172, dtype: object
173 Name    Croconaw
HP            65
Name: 173, dtype: object
174 Name    Feraligatr
HP              85
Name: 174, dtype: object
175 Name    Sentret
HP           35
Name: 175, dtype: object
176 Name    Furret
HP          85
Name: 176, dtype: object
177 Name    Hoothoot
HP            60
Name: 177, dtype: object
178 Name    Noctowl
HP          100
Name: 178, dtype: object
179 Name    Ledyba
HP          40
Name: 179, dtype: object
180 Name    Ledian
HP          55
Name: 180, dtype: object
181 Name    Spinarak
HP            40
Name: 181, dtype: object
182 Name    Ariados
HP           70
Name: 182, dtype: object
183 Name    Crobat
HP          85
Name: 183, dtype: object
184 Name    Chinchou
HP            75
Name: 184, dtype: object
185 Name    Lanturn
HP          125
Name: 185, dtype: object
186 Name    Pichu
HP         20
Name: 186, dtype: object
187 Name    Cleffa
HP          50
Name: 187, dtype: object
188 Name    Igglybuff
HP             90
Name: 188, dtype: object
189 Name    Togepi
HP          35
Name: 189, dtype: object
190 Name    Togetic
HP           55
Name: 190, dtype: object
191 Name    Natu
HP        40
Name: 191, dtype: object
192 Name    Xatu
HP        65
Name: 192, dtype: object
193 Name    Mareep
HP          55
Name: 193, dtype: object
194 Name    Flaaffy
HP           70
Name: 194, dtype: object
195 Name    Ampharos
HP            90
Name: 195, dtype: object
196 Name    AmpharosMega Ampharos
HP                         90
Name: 196, dtype: object
197 Name    Bellossom
HP             75
Name: 197, dtype: object
198 Name    Marill
HP          70
Name: 198, dtype: object
199 Name    Azumarill
HP            100
Name: 199, dtype: object
200 Name    Sudowoodo
HP             70
Name: 200, dtype: object
201 Name    Politoed
HP            90
Name: 201, dtype: object
202 Name    Hoppip
HP          35
Name: 202, dtype: object
203 Name    Skiploom
HP            55
Name: 203, dtype: object
204 Name    Jumpluff
HP            75
Name: 204, dtype: object
205 Name    Aipom
HP         55
Name: 205, dtype: object
206 Name    Sunkern
HP           30
Name: 206, dtype: object
207 Name    Sunflora
HP            75
Name: 207, dtype: object
208 Name    Yanma
HP         65
Name: 208, dtype: object
209 Name    Wooper
HP          55
Name: 209, dtype: object
210 Name    Quagsire
HP            95
Name: 210, dtype: object
211 Name    Espeon
HP          65
Name: 211, dtype: object
212 Name    Umbreon
HP           95
Name: 212, dtype: object
213 Name    Murkrow
HP           60
Name: 213, dtype: object
214 Name    Slowking
HP            95
Name: 214, dtype: object
215 Name    Misdreavus
HP              60
Name: 215, dtype: object
216 Name    Unown
HP         48
Name: 216, dtype: object
217 Name    Wobbuffet
HP            190
Name: 217, dtype: object
218 Name    Girafarig
HP             70
Name: 218, dtype: object
219 Name    Pineco
HP          50
Name: 219, dtype: object
220 Name    Forretress
HP              75
Name: 220, dtype: object
221 Name    Dunsparce
HP            100
Name: 221, dtype: object
222 Name    Gligar
HP          65
Name: 222, dtype: object
223 Name    Steelix
HP           75
Name: 223, dtype: object
224 Name    SteelixMega Steelix
HP                       75
Name: 224, dtype: object
225 Name    Snubbull
HP            60
Name: 225, dtype: object
226 Name    Granbull
HP            90
Name: 226, dtype: object
227 Name    Qwilfish
HP            65
Name: 227, dtype: object
228 Name    Scizor
HP          70
Name: 228, dtype: object
229 Name    ScizorMega Scizor
HP                     70
Name: 229, dtype: object
230 Name    Shuckle
HP           20
Name: 230, dtype: object
231 Name    Heracross
HP             80
Name: 231, dtype: object
232 Name    HeracrossMega Heracross
HP                           80
Name: 232, dtype: object
233 Name    Sneasel
HP           55
Name: 233, dtype: object
234 Name    Teddiursa
HP             60
Name: 234, dtype: object
235 Name    Ursaring
HP            90
Name: 235, dtype: object
236 Name    Slugma
HP          40
Name: 236, dtype: object
237 Name    Magcargo
HP            50
Name: 237, dtype: object
238 Name    Swinub
HP          50
Name: 238, dtype: object
239 Name    Piloswine
HP            100
Name: 239, dtype: object
240 Name    Corsola
HP           55
Name: 240, dtype: object
241 Name    Remoraid
HP            35
Name: 241, dtype: object
242 Name    Octillery
HP             75
Name: 242, dtype: object
243 Name    Delibird
HP            45
Name: 243, dtype: object
244 Name    Mantine
HP           65
Name: 244, dtype: object
245 Name    Skarmory
HP            65
Name: 245, dtype: object
246 Name    Houndour
HP            45
Name: 246, dtype: object
247 Name    Houndoom
HP            75
Name: 247, dtype: object
248 Name    HoundoomMega Houndoom
HP                         75
Name: 248, dtype: object
249 Name    Kingdra
HP           75
Name: 249, dtype: object
250 Name    Phanpy
HP          90
Name: 250, dtype: object
251 Name    Donphan
HP           90
Name: 251, dtype: object
252 Name    Porygon2
HP            85
Name: 252, dtype: object
253 Name    Stantler
HP            73
Name: 253, dtype: object
254 Name    Smeargle
HP            55
Name: 254, dtype: object
255 Name    Tyrogue
HP           35
Name: 255, dtype: object
256 Name    Hitmontop
HP             50
Name: 256, dtype: object
257 Name    Smoochum
HP            45
Name: 257, dtype: object
258 Name    Elekid
HP          45
Name: 258, dtype: object
259 Name    Magby
HP         45
Name: 259, dtype: object
260 Name    Miltank
HP           95
Name: 260, dtype: object
261 Name    Blissey
HP          255
Name: 261, dtype: object
262 Name    Raikou
HP          90
Name: 262, dtype: object
263 Name    Entei
HP        115
Name: 263, dtype: object
264 Name    Suicune
HP          100
Name: 264, dtype: object
265 Name    Larvitar
HP            50
Name: 265, dtype: object
266 Name    Pupitar
HP           70
Name: 266, dtype: object
267 Name    Tyranitar
HP            100
Name: 267, dtype: object
268 Name    TyranitarMega Tyranitar
HP                          100
Name: 268, dtype: object
269 Name    Lugia
HP        106
Name: 269, dtype: object
270 Name    Ho-oh
HP        106
Name: 270, dtype: object
271 Name    Celebi
HP         100
Name: 271, dtype: object
272 Name    Treecko
HP           40
Name: 272, dtype: object
273 Name    Grovyle
HP           50
Name: 273, dtype: object
274 Name    Sceptile
HP            70
Name: 274, dtype: object
275 Name    SceptileMega Sceptile
HP                         70
Name: 275, dtype: object
276 Name    Torchic
HP           45
Name: 276, dtype: object
277 Name    Combusken
HP             60
Name: 277, dtype: object
278 Name    Blaziken
HP            80
Name: 278, dtype: object
279 Name    BlazikenMega Blaziken
HP                         80
Name: 279, dtype: object
280 Name    Mudkip
HP          50
Name: 280, dtype: object
281 Name    Marshtomp
HP             70
Name: 281, dtype: object
282 Name    Swampert
HP           100
Name: 282, dtype: object
283 Name    SwampertMega Swampert
HP                        100
Name: 283, dtype: object
284 Name    Poochyena
HP             35
Name: 284, dtype: object
285 Name    Mightyena
HP             70
Name: 285, dtype: object
286 Name    Zigzagoon
HP             38
Name: 286, dtype: object
287 Name    Linoone
HP           78
Name: 287, dtype: object
288 Name    Wurmple
HP           45
Name: 288, dtype: object
289 Name    Silcoon
HP           50
Name: 289, dtype: object
290 Name    Beautifly
HP             60
Name: 290, dtype: object
291 Name    Cascoon
HP           50
Name: 291, dtype: object
292 Name    Dustox
HP          60
Name: 292, dtype: object
293 Name    Lotad
HP         40
Name: 293, dtype: object
294 Name    Lombre
HP          60
Name: 294, dtype: object
295 Name    Ludicolo
HP            80
Name: 295, dtype: object
296 Name    Seedot
HP          40
Name: 296, dtype: object
297 Name    Nuzleaf
HP           70
Name: 297, dtype: object
298 Name    Shiftry
HP           90
Name: 298, dtype: object
299 Name    Taillow
HP           40
Name: 299, dtype: object
300 Name    Swellow
HP           60
Name: 300, dtype: object
301 Name    Wingull
HP           40
Name: 301, dtype: object
302 Name    Pelipper
HP            60
Name: 302, dtype: object
303 Name    Ralts
HP         28
Name: 303, dtype: object
304 Name    Kirlia
HP          38
Name: 304, dtype: object
305 Name    Gardevoir
HP             68
Name: 305, dtype: object
306 Name    GardevoirMega Gardevoir
HP                           68
Name: 306, dtype: object
307 Name    Surskit
HP           40
Name: 307, dtype: object
308 Name    Masquerain
HP              70
Name: 308, dtype: object
309 Name    Shroomish
HP             60
Name: 309, dtype: object
310 Name    Breloom
HP           60
Name: 310, dtype: object
311 Name    Slakoth
HP           60
Name: 311, dtype: object
312 Name    Vigoroth
HP            80
Name: 312, dtype: object
313 Name    Slaking
HP          150
Name: 313, dtype: object
314 Name    Nincada
HP           31
Name: 314, dtype: object
315 Name    Ninjask
HP           61
Name: 315, dtype: object
316 Name    Shedinja

In [3]:
df_a = pd.read_csv('Pokemon_data.txt',sep='\t')
print(df_a)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [4]:
df_a = pd.read_csv('Pokemon_data.txt')
print(df_a)

    #\tName\tType 1\tType 2\tHP\tAttack\tDefense\tSp. Atk\tSp. Def\tSpeed\tGeneration\tLegendary
0    1\tBulbasaur\tGrass\tPoison\t45\t49\t49\t65\t6...
1    2\tIvysaur\tGrass\tPoison\t60\t62\t63\t80\t80\...
2    3\tVenusaur\tGrass\tPoison\t80\t82\t83\t100\t1...
3    3\tVenusaurMega Venusaur\tGrass\tPoison\t80\t1...
4    4\tCharmander\tFire\t\t39\t52\t43\t60\t50\t65\...
..                                                 ...
795  719\tDiancie\tRock\tFairy\t50\t100\t150\t100\t...
796  719\tDiancieMega Diancie\tRock\tFairy\t50\t160...
797  720\tHoopaHoopa Confined\tPsychic\tGhost\t80\t...
798  720\tHoopaHoopa Unbound\tPsychic\tDark\t80\t16...
799  721\tVolcanion\tFire\tWater\t80\t110\t120\t130...

[800 rows x 1 columns]

In [5]:
import seaborn

ModuleNotFoundError: No module named 'seaborn'

In [2]:
print(df_a)

NameError: name 'df_a' is not defined

In [3]:
impodf_aa = pd.read_csv('Pokemon_data.txt')
print(df_aa)

NameError: name 'pd' is not defined

In [12]:
df_a

    #\tName\tType 1\tType 2\tHP\tAttack\tDefense\tSp. Atk\tSp. Def\tSpeed\tGeneration\tLegendary
0    1\tBulbasaur\tGrass\tPoison\t45\t49\t49\t65\t6...
1    2\tIvysaur\tGrass\tPoison\t60\t62\t63\t80\t80\...
2    3\tVenusaur\tGrass\tPoison\t80\t82\t83\t100\t1...
3    3\tVenusaurMega Venusaur\tGrass\tPoison\t80\t1...
4    4\tCharmander\tFire\t\t39\t52\t43\t60\t50\t65\...
..                                                 ...
795  719\tDiancie\tRock\tFairy\t50\t100\t150\t100\t...
796  719\tDiancieMega Diancie\tRock\tFairy\t50\t160...
797  720\tHoopaHoopa Confined\tPsychic\tGhost\t80\t...
798  720\tHoopaHoopa Unbound\tPsychic\tDark\t80\t16...
799  721\tVolcanion\tFire\tWater\t80\t110\t120\t130...

[800 rows x 1 columns]

In [13]:
df_aa

    #\tName\tType 1\tType 2\tHP\tAttack\tDefense\tSp. Atk\tSp. Def\tSpeed\tGeneration\tLegendary
0    1\tBulbasaur\tGrass\tPoison\t45\t49\t49\t65\t6...
1    2\tIvysaur\tGrass\tPoison\t60\t62\t63\t80\t80\...
2    3\tVenusaur\tGrass\tPoison\t80\t82\t83\t100\t1...
3    3\tVenusaurMega Venusaur\tGrass\tPoison\t80\t1...
4    4\tCharmander\tFire\t\t39\t52\t43\t60\t50\t65\...
..                                                 ...
795  719\tDiancie\tRock\tFairy\t50\t100\t150\t100\t...
796  719\tDiancieMega Diancie\tRock\tFairy\t50\t160...
797  720\tHoopaHoopa Confined\tPsychic\tGhost\t80\t...
798  720\tHoopaHoopa Unbound\tPsychic\tDark\t80\t16...
799  721\tVolcanion\tFire\tWater\t80\t110\t120\t130...

[800 rows x 1 columns]